# -*- coding: utf-8 -*-
"""calculator.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kKNDPxd-mCJgwrsX2WH-l-FBJT0iNqs6
"""

first=int(input("Enter a number:"))
second=int(input("Enter a number:"))
operator =input("Enter operator (+,-,*,/,%,**):")


if operator=="+":
  print(first+second)
elif operator=="-":
  print(first-second)
elif operator=="*":
  print(first*second)
elif operator=="/":
  print(first/second)
elif operator=="%":
  print(first%second)
elif operator=="**":
  print(first**second)
else:
  print("Invalid Operation")